version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "9999:80"
        expose:
            - 80
        volumes:
            - ./htdocs:/public
            - ./default.conf:/etc/nginx/conf.d/default.conf
        environment:
          - VIRTUAL_HOST=api.localhost
    php:
        image: php:fpm
        volumes:
            - ./htdocs:/public
networks:
  default:
    external:
      name: environments_development